kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: imichael-service

spec:
  ports:
    # Accept traffic sent to port 80
    - name: nginx-port
      port: 80
      targetPort: 80

  type: LoadBalancer
